services:
  app:
    container_name: trip-planner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - trip-planner-database
    env_file:
      - .env

  trip-planner-database:
    container_name: trip-planner-database
    image: bitnami/postgresql:latest
    ports:
      - '5482:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
